name: Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["Docker and Trivy"]
    types:
      - completed
    branches:
      - main

env:
  REGION: europe-west1
  PROJECT_ID: 688932068099
  DOCKER_IMAGE: robounce/isen-python:dev-${{ github.sha }}
  GCP_IMAGE: europe-west1-docker.pkg.dev/isen-python-458207/isen-python-robin-app/isen-python

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy application
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Authenticate Docker to Artifact Registry
      run: |
        gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull image from Docker Hub
      run: |
        docker pull $DOCKER_IMAGE

    - name: Tag image for Artifact Registry
      run: |
        docker tag $DOCKER_IMAGE $GCP_IMAGE

    - name: Push image to Artifact Registry
      run: |
        docker push $GCP_IMAGE

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: isen-python-service
        image: europe-west1-docker.pkg.dev/isen-python-458207/isen-python-robin-app/isen-python
        region: europe-west1
        flags: |
        --allow-unauthenticated
        --update-labels managed-by=github-actions,commit-sha=${{ github.sha }}
        --timeout 900s