name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    container:
      image: cypress/browsers:22.12.0
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        run: |
          apt-get update
          apt-get install -y python3 python3-pip

      - name: Install dependencies and start server
        run: |
          pip3 install -r requirements.txt
          python3 manage.py runserver 0.0.0.0:8080 &
          sleep 5

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
