name: DAST Scan with ZAP

on:
  push:
    branches:
      - main

jobs:
  dast-scan:
    name: Run DAST with ZAP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Start application (Assuming Flask, Django, etc. with port 8080)
        run: |
          python manage.py runserver 0.0.0.0:8080 &
          sleep 10  # Wait for the server to start

      - name: Run ZAP Baseline
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-t 60 -J zap-report.json -w report_md.md -r report_html.html -config api.disablekey=true'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: zap-report.json
