name: Docker and Trivy

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: robounce
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: robounce/isen-python:dev-${{ github.sha }}
          cache-from: type=registry,ref=robounce/isen-python:latest
          cache-to: type=inline
  
  security-scan:
    needs: build-and-push
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/robounce/isen-python:dev-${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          continue-on-error: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'



  sbom:
    needs: build-and-push
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    
    steps:
    - name: Scan the image and upload dependency results
      uses: anchore/sbom-action@bb716408e75840bbb01e839347cd213767269d4a
      with:
        image-ref: 'docker.io/robounce/isen-python:dev-${{ github.sha }}'
        artifact-name: image.spdx.json
        dependency-snapshot: true
