name: Docker and Trivy

on: push

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/isen-python:dev-${{ github.sha }}
          cache-from: type=registry,ref=${{secrets.DOCKERHUB_USERNAME}}/isen-python:latest
          cache-to: type=inline
  
  security-scan:
    needs: docker-build
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/${{secrets.DOCKERHUB_USERNAME}}/isen-python:dev-${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          continue-on-error: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  cypress:
    needs: docker-build
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome106-ff106
      options: --user 1001
    services:
      app:
        image: ${{secrets.DOCKERHUB_USERNAME}}/isen-python:dev-${{ github.sha }}
        ports:
          - 8080:8080
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          cd cypress
          npm install
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: cypress
          browser: chrome
          config: baseUrl=http://app:8080
        env:
          CYPRESS_baseUrl: http://app:8080